# action.yml
name: 'CFML Unit Tests'
description: 'Run CFML unit tests using TestBox'
inputs:
  cfml-engine:  # id of input
    description: 'The CFML engine to test against'
    required: true
    default: 'lucee@5'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.cfml-engine }}