on: [push]

jobs:
    job:
        runs-on: ubuntu-latest
        name: A job to test some code
        steps:
        - run: |
            echo Starting the build
            curl --location -o /tmp/box.zip https://www.ortussolutions.com/parent/download/commandbox/type/bin
            unzip /tmp/box.zip -d /tmp/
            chmod a+x /tmp/box
            /tmp/box install production=false
            /tmp/box server start cfengine=lucee@4
            mkdir /tmp/results/
            /tmp/box testbox run outputFile=testbox-lucee4.xml reporter=junit